name: Vérification dispo Maiia

on:
  schedule:
    - cron: "*/15 * * * *"  # toutes les 15 minutes
  workflow_dispatch:

jobs:
  check-rdv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: Upload debug fichiers
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            page_dump.html
            page_debug.png
            avant_motif_btn.png
