name: Surveillance Maiia

on:
  schedule:
    - cron: '*/10 * * * *'  # Toutes les 10 minutes
  workflow_dispatch:        # Lancement manuel

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances Python
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests
          
      - name: Debug version Chrome/Driver
        run: |
          google-chrome --version
          which chromedriver || echo "ChromeDriver pas encore installé"

      - name: Installer une version stable de Google Chrome
        run: |
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_124.0.6367.60-1_amd64.deb
          sudo dpkg -i google-chrome-stable_124.0.6367.60-1_amd64.deb || sudo apt-get -f install -y

      - name: Installer ChromeDriver pour cette version
        run: |
          wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/124.0.6367.60/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Exécuter le script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
